### ISSUE TITLE
Combatify modifies shield animation in third person

### ISSUE THREAD

**Issue by StunfMC** [Alexandra-Myers/Combatify#47]
The third person shield animation with Combatify installed has incorrect positioning for a frame during blocking, making the shield animation look choppy.

**Comment by Alexandra-Myers** [comment]
technically fixed but cannot be completely fixed

**Comment by DreamSt4n** [comment]
This is still an issue. Please reopen.

**Comment by Alexandra-Myers** [comment]
do you have sword blocking enabled?

**Comment by DreamSt4n** [comment]
No, but the issue persists either way.

**Comment by StunfMC** [comment]
Technically fixed in this [commit](https://github.com/Alexandra-Myers/Combatify/commit/5b5c2256abfe478696c8817009b982049d087bd2) but breaks sword blocking due to some modifications.

**Comment by zOnlyKroks** [comment]
by removing sword blocking ;V

**Comment by StunfMC** [comment]
It still exists, all I did was prevent the sword blocking to generate. I explained this in my comment, and rewriting the sword blocking code is the only way to fix this bug. I don’t plan on my commit being used since it breaks Sword Blocking but it’s just an idea with rewriting the code.

**Comment by Alexandra-Myers** [comment]
The issue is, you don't even understand what that code does. It's not even the code responsible for causing this issue. This is just a band-aid fix which doesn't fix the underlying issue.

**Comment by StunfMC** [comment]
I’m not saying it is the code responsible, and I am not planning this commit to be used. It’s just a proposed “fix” but it breaks Sword Blocking. I have plans to take a further look and I apologize if I didn’t make myself clear before.

**Comment by Alexandra-Myers** [comment]
Anyways, fixed in 1.1.8.1, better solution needed but should be fine for most.
